# Generated by Django 4.2.5 on 2023-10-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_floor', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('moving_up', 'Moving Up'), ('moving_down', 'Moving Down'), ('maintenance', 'Maintenance')], default='stopped', max_length=15)),
                ('operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to', to='elevator_api.floor')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_api.elevator')),
                ('from_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_from', to='elevator_api.floor')),
            ],
        ),
    ]
