# Generated by Django 4.2.5 on 2023-10-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='current_floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
