# Generated by Django 4.2.5 on 2023-10-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0004_rename_request_elevatorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='door_open',
            field=models.BooleanField(default=False),
        ),
    ]
