# Generated by Django 4.2.5 on 2023-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0006_elevatorsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='elevator_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
