# Generated by Django 4.2.5 on 2023-10-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0007_elevator_elevator_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevatorsystem',
            name='elevators',
        ),
        migrations.RemoveField(
            model_name='elevatorsystem',
            name='floors',
        ),
        migrations.AddField(
            model_name='elevatorsystem',
            name='elevators',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elevator_api.elevator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevatorsystem',
            name='floors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elevator_api.floor'),
            preserve_default=False,
        ),
    ]
